TrainerNames:
	db "Youngster@"
	db "Bug Catcher@"
	db "Lass@"
	db "Sailor@"
	db "Jr.Trainer♂@"
	db "Jr.Trainer♀@"
	db "Pokémaniac@"
	db "Super Nerd@"
	db "Hiker@"
	db "Biker@"
	db "Burglar@"
	db "Engineer@"
	db "Rocket@"
	db "Fisherman@"
	db "Swimmer♂@"
	db "Cue Ball@"
	db "Gambler@"
	db "Beauty@"
	db "Psychic@"
	db "Rocker@"
	db "Juggler@"
	db "Tamer@"
	db "Bird Keeper@"
	db "Blackbelt@"
	db "RIVAL1@"
	db "Prof.Oak@"
	db "Giovanni@"
	db "Scientist@"
	db "Giovanni@"
	db "Rocket@"
	db "Cooltrainer♂@"
	db "Cooltrainer♀@"
	db "Bruno@"
	db "Brock@"
	db "Misty@"
	db "Lt.Surge@"
	db "Erika@"
	db "Koga@"
	db "Blaine@"
	db "Sabrina@"
	db "Gentleman@"
	db "RIVAL2@"
	db "RIVAL3@"
	db "Lorelei@"
	db "Channeler@"
	db "Agatha@"
	db "Lance@"
	db "Swimmer♀@"
